[package]
name = "live-region"
description = "Simple screen reader output in wxDragon applications"
version = "0.1.4"
readme = "README.md"
repository = "https://github.com/trypsynth/live-region"
keywords = ["gui", "ui", "utility", "windows"]
categories = ["accessibility", "gui"]
license = "MIT"
edition = "2024"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ['cfg(feature, values("cargo-clippy"))']

[dependencies]
wxdragon = "0.9.15"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_UI_Accessibility", "Win32_System_Com", "Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Ole", "Win32_System_Variant"] }
